### ISSUE TITLE
Installed dotnet-sdk-7.0.100-rc.1.22431.12-freebsd-x64.tar.gz ;Missing Microsoft.NETCore.App.Host.freebsd-x64

### ISSUE THREAD

**Issue by devosalain** [Thefrank/dotnet-freebsd-native-binaries#2]
I untarred dotnet-sdk-7.0.100-rc.1.22431.12-freebsd-x64.tar.gz to /usr/share/dotnet/
But when i compile and run an F# UI application :
dotnet new --install JaggerJo.Avalonia.FuncUI.Templates
dotnet new funcui.basic -n NewApp
dotnet run , the error given is :

/usr/home/x/dotnet2/NewApp/NewApp.fsproj : error NU1101: Unable to find package Microsoft.NETCore.App.Host.freebsd-x64. No packages exist with this id in source(s): /usr/share/dotnet/sdk/7.0.100-rc.1.22431.12/FSharp/library-packs, nuget.org
The build failed. Fix the build errors and run again.

**Comment by Thefrank** [comment]
You will also need:
- Microsoft.NETCore.App.Host.freebsd-x64.VERSION.nupkg
- Microsoft.NETCore.App.Runtime.freebsd-x64.VERSION.nupkg
- Microsoft.AspNetCore.App.Runtime.freebsd-x64.VERSION.nupkg


Somewhere that dotnet can find them (e.g., a `dotnet nuget` source location or a URI listed in the `NuGet.config` that your build is using)

**Comment by devosalain** [comment]
I'm sorry i'm a bit new to it. "/var/cache/nuget" is empty.
Which explicit commands do i need to execute to install those 3 packages ? [From where]

**Comment by Thefrank** [comment]
you can just download the packages into that location (`fetch`, `curl`, or `wget` will all work) then either:

- manually add the location to the NuGet.config of your project (see here: https://learn.microsoft.com/en-us/nuget/reference/nuget-config-file#packagesources)
- add the location as a source using `dotnet` (e.g., `dotnet nuget add source --name "some name" /var/cache/nuget`)

**Comment by sec** [comment]
@devosalain you can also try to use https://github.com/sec/dotnet-freebsd-nuget-feed

**Comment by Thefrank** [comment]
Closing. This is likely an upstream issue with most tools/projects not being aware of FreeBSD :(
